name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Run Node.js Script
        run: |
          # Run your Node.js code here without reinstalling Node.js
          # For example, you can run a JavaScript file like this:
          # node your-script.js
          # Replace 'your-script.js' with the actual name of your script.
          node your-script.js

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build (if present)
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
